/* generated by pull.js */
import _js from "./userscript.js";
import _css from "!css-loader!./style.css";
import _asset from "!raw-loader!./fill-complex-gradient-enabled.svg";
import _asset2 from "!url-loader!./add.svg";
import _asset3 from "!url-loader!./delete.svg";
export const resources = {
  "userscript.js": _js,
  "style.css": _css,
  "fill-complex-gradient-enabled.svg": _asset,
  "add.svg": _asset2,
  "delete.svg": _asset3,
};
